/**
 * Comprehensive city-to-IANA-timezone mapping.
 * Keys are lowercase city names / aliases. Values are IANA timezone IDs.
 * Enables searching by any city name, not just IANA representative cities.
 */
export const CITY_TIMEZONE_MAP: Record<string, string> = {
  // ── United States ──────────────────────────────────────────────────────────
  'new york': 'America/New_York',
  'nyc': 'America/New_York',
  'new york city': 'America/New_York',
  'manhattan': 'America/New_York',
  'brooklyn': 'America/New_York',
  'queens': 'America/New_York',
  'bronx': 'America/New_York',
  'staten island': 'America/New_York',
  'jersey city': 'America/New_York',
  'newark': 'America/New_York',
  'hoboken': 'America/New_York',
  'yonkers': 'America/New_York',
  'buffalo': 'America/New_York',
  'rochester': 'America/New_York',
  'albany': 'America/New_York',
  'syracuse': 'America/New_York',
  'boston': 'America/New_York',
  'cambridge': 'America/New_York',
  'worcester': 'America/New_York',
  'providence': 'America/New_York',
  'hartford': 'America/New_York',
  'bridgeport': 'America/New_York',
  'new haven': 'America/New_York',
  'stamford': 'America/New_York',
  'philadelphia': 'America/New_York',
  'philly': 'America/New_York',
  'pittsburgh': 'America/New_York',
  'allentown': 'America/New_York',
  'baltimore': 'America/New_York',
  'washington dc': 'America/New_York',
  'washington d.c.': 'America/New_York',
  'dc': 'America/New_York',
  'arlington': 'America/New_York',
  'alexandria': 'America/New_York',
  'richmond': 'America/New_York',
  'norfolk': 'America/New_York',
  'virginia beach': 'America/New_York',
  'charlotte': 'America/New_York',
  'raleigh': 'America/New_York',
  'durham': 'America/New_York',
  'greensboro': 'America/New_York',
  'charleston': 'America/New_York',
  'columbia sc': 'America/New_York',
  'atlanta': 'America/New_York',
  'savannah': 'America/New_York',
  'jacksonville': 'America/New_York',
  'orlando': 'America/New_York',
  'tampa': 'America/New_York',
  'st. petersburg': 'America/New_York',
  'miami': 'America/New_York',
  'fort lauderdale': 'America/New_York',
  'west palm beach': 'America/New_York',
  'naples fl': 'America/New_York',
  'fort myers': 'America/New_York',
  'tallahassee': 'America/New_York',
  'gainesville': 'America/New_York',
  'cleveland': 'America/New_York',
  'columbus': 'America/New_York',
  'cincinnati': 'America/New_York',
  'akron': 'America/New_York',
  'toledo': 'America/New_York',
  'dayton': 'America/New_York',
  'detroit': 'America/Detroit',
  'grand rapids': 'America/Detroit',
  'ann arbor': 'America/Detroit',
  'lansing': 'America/Detroit',
  'flint': 'America/Detroit',
  'indianapolis': 'America/Indiana/Indianapolis',
  'fort wayne': 'America/Indiana/Indianapolis',
  'evansville': 'America/Indiana/Indianapolis',
  'louisville': 'America/Kentucky/Louisville',
  'lexington': 'America/Kentucky/Louisville',
  'knoxville': 'America/New_York',
  'nashville': 'America/Chicago',
  'memphis': 'America/Chicago',
  'chattanooga': 'America/New_York',
  'chicago': 'America/Chicago',
  'aurora il': 'America/Chicago',
  'rockford': 'America/Chicago',
  'joliet': 'America/Chicago',
  'naperville': 'America/Chicago',
  'springfield il': 'America/Chicago',
  'peoria': 'America/Chicago',
  'elgin': 'America/Chicago',
  'milwaukee': 'America/Chicago',
  'madison wi': 'America/Chicago',
  'green bay': 'America/Chicago',
  'minneapolis': 'America/Chicago',
  'st. paul': 'America/Chicago',
  'duluth': 'America/Chicago',
  'des moines': 'America/Chicago',
  'cedar rapids': 'America/Chicago',
  'kansas city': 'America/Chicago',
  'wichita': 'America/Chicago',
  'omaha': 'America/Chicago',
  'lincoln ne': 'America/Chicago',
  'st. louis': 'America/Chicago',
  'saint louis': 'America/Chicago',
  'springfield mo': 'America/Chicago',
  'columbia mo': 'America/Chicago',
  'little rock': 'America/Chicago',
  'tulsa': 'America/Chicago',
  'oklahoma city': 'America/Chicago',
  'dallas': 'America/Chicago',
  'fort worth': 'America/Chicago',
  'houston': 'America/Chicago',
  'san antonio': 'America/Chicago',
  'austin': 'America/Chicago',
  'el paso': 'America/Denver',
  'corpus christi': 'America/Chicago',
  'lubbock': 'America/Chicago',
  'amarillo': 'America/Chicago',
  'new orleans': 'America/Chicago',
  'baton rouge': 'America/Chicago',
  'shreveport': 'America/Chicago',
  'jackson ms': 'America/Chicago',
  'birmingham': 'America/Chicago',
  'montgomery': 'America/Chicago',
  'mobile': 'America/Chicago',
  'denver': 'America/Denver',
  'colorado springs': 'America/Denver',
  'aurora co': 'America/Denver',
  'boulder': 'America/Denver',
  'fort collins': 'America/Denver',
  'pueblo': 'America/Denver',
  'salt lake city': 'America/Denver',
  'provo': 'America/Denver',
  'ogden': 'America/Denver',
  'albuquerque': 'America/Denver',
  'santa fe': 'America/Denver',
  'billings': 'America/Denver',
  'boise': 'America/Boise',
  'phoenix': 'America/Phoenix',
  'tucson': 'America/Phoenix',
  'mesa': 'America/Phoenix',
  'chandler': 'America/Phoenix',
  'scottsdale': 'America/Phoenix',
  'tempe': 'America/Phoenix',
  'glendale az': 'America/Phoenix',
  'las vegas': 'America/Los_Angeles',
  'henderson nv': 'America/Los_Angeles',
  'reno': 'America/Los_Angeles',
  'los angeles': 'America/Los_Angeles',
  'la': 'America/Los_Angeles',
  'san diego': 'America/Los_Angeles',
  'san jose': 'America/Los_Angeles',
  'san francisco': 'America/Los_Angeles',
  'sf': 'America/Los_Angeles',
  'fresno': 'America/Los_Angeles',
  'sacramento': 'America/Los_Angeles',
  'long beach': 'America/Los_Angeles',
  'oakland': 'America/Los_Angeles',
  'bakersfield': 'America/Los_Angeles',
  'anaheim': 'America/Los_Angeles',
  'santa ana': 'America/Los_Angeles',
  'riverside': 'America/Los_Angeles',
  'stockton': 'America/Los_Angeles',
  'irvine': 'America/Los_Angeles',
  'chula vista': 'America/Los_Angeles',
  'fremont': 'America/Los_Angeles',
  'modesto': 'America/Los_Angeles',
  'oxnard': 'America/Los_Angeles',
  'fontana': 'America/Los_Angeles',
  'santa clarita': 'America/Los_Angeles',
  'glendale ca': 'America/Los_Angeles',
  'seattle': 'America/Los_Angeles',
  'spokane': 'America/Los_Angeles',
  'tacoma': 'America/Los_Angeles',
  'bellevue wa': 'America/Los_Angeles',
  'portland': 'America/Los_Angeles',
  'eugene': 'America/Los_Angeles',
  'anchorage': 'America/Anchorage',
  'fairbanks': 'America/Anchorage',
  'juneau': 'America/Juneau',
  'honolulu': 'Pacific/Honolulu',
  'hilo': 'Pacific/Honolulu',
  'maui': 'Pacific/Honolulu',

  // ── Canada ────────────────────────────────────────────────────────────────
  'toronto': 'America/Toronto',
  'ottawa': 'America/Toronto',
  'hamilton on': 'America/Toronto',
  'london on': 'America/Toronto',
  'kitchener': 'America/Toronto',
  'mississauga': 'America/Toronto',
  'brampton': 'America/Toronto',
  'markham': 'America/Toronto',
  'vaughan': 'America/Toronto',
  'montreal': 'America/Toronto',
  'quebec city': 'America/Toronto',
  'laval': 'America/Toronto',
  'longueuil': 'America/Toronto',
  'gatineau': 'America/Toronto',
  'sherbrooke': 'America/Toronto',
  'halifax': 'America/Halifax',
  'moncton': 'America/Moncton',
  'fredericton': 'America/Moncton',
  'saint john nb': 'America/Moncton',
  'winnipeg': 'America/Winnipeg',
  'brandon': 'America/Winnipeg',
  'regina': 'America/Regina',
  'saskatoon': 'America/Regina',
  'calgary': 'America/Edmonton',
  'edmonton': 'America/Edmonton',
  'red deer': 'America/Edmonton',
  'lethbridge': 'America/Edmonton',
  'vancouver': 'America/Vancouver',
  'surrey': 'America/Vancouver',
  'burnaby': 'America/Vancouver',
  'richmond bc': 'America/Vancouver',
  'kelowna': 'America/Vancouver',
  'victoria bc': 'America/Vancouver',
  'st. john\'s': 'America/St_Johns',
  'corner brook': 'America/St_Johns',

  // ── Mexico ────────────────────────────────────────────────────────────────
  'mexico city': 'America/Mexico_City',
  'cdmx': 'America/Mexico_City',
  'guadalajara': 'America/Mexico_City',
  'monterrey': 'America/Monterrey',
  'puebla': 'America/Mexico_City',
  'tijuana': 'America/Tijuana',
  'leon': 'America/Mexico_City',
  'ciudad juarez': 'America/Ojinaga',
  'juarez': 'America/Ojinaga',
  'cancun': 'America/Cancun',
  'merida': 'America/Merida',
  'acapulco': 'America/Mexico_City',
  'hermosillo': 'America/Hermosillo',
  'chihuahua': 'America/Chihuahua',
  'mazatlan': 'America/Mazatlan',
  'culiacan': 'America/Mazatlan',

  // ── United Kingdom ────────────────────────────────────────────────────────
  'london': 'Europe/London',
  'birmingham uk': 'Europe/London',
  'manchester': 'Europe/London',
  'leeds': 'Europe/London',
  'glasgow': 'Europe/London',
  'liverpool': 'Europe/London',
  'sheffield': 'Europe/London',
  'bristol': 'Europe/London',
  'edinburgh': 'Europe/London',
  'cardiff': 'Europe/London',
  'belfast': 'Europe/London',
  'newcastle': 'Europe/London',
  'coventry': 'Europe/London',
  'leicester': 'Europe/London',
  'nottingham': 'Europe/London',
  'bradford': 'Europe/London',
  'stoke': 'Europe/London',
  'wolverhampton': 'Europe/London',
  'derby': 'Europe/London',
  'southampton': 'Europe/London',
  'portsmouth': 'Europe/London',
  'oxford': 'Europe/London',
  'cambridge uk': 'Europe/London',
  'reading': 'Europe/London',
  'luton': 'Europe/London',
  'milton keynes': 'Europe/London',
  'norwich': 'Europe/London',
  'brighton': 'Europe/London',
  'hull': 'Europe/London',
  'york': 'Europe/London',
  'exeter': 'Europe/London',
  'swansea': 'Europe/London',
  'aberdeen': 'Europe/London',
  'dundee': 'Europe/London',
  'inverness': 'Europe/London',

  // ── Ireland ───────────────────────────────────────────────────────────────
  'dublin': 'Europe/Dublin',
  'cork': 'Europe/Dublin',
  'limerick': 'Europe/Dublin',
  'galway': 'Europe/Dublin',
  'waterford': 'Europe/Dublin',
  'drogheda': 'Europe/Dublin',

  // ── France ────────────────────────────────────────────────────────────────
  'paris': 'Europe/Paris',
  'marseille': 'Europe/Paris',
  'lyon': 'Europe/Paris',
  'toulouse': 'Europe/Paris',
  'nice': 'Europe/Paris',
  'nantes': 'Europe/Paris',
  'strasbourg': 'Europe/Paris',
  'montpellier': 'Europe/Paris',
  'bordeaux': 'Europe/Paris',
  'lille': 'Europe/Paris',
  'rennes': 'Europe/Paris',
  'reims': 'Europe/Paris',
  'le havre': 'Europe/Paris',
  'dijon': 'Europe/Paris',
  'grenoble': 'Europe/Paris',
  'angers': 'Europe/Paris',
  'villeurbanne': 'Europe/Paris',

  // ── Germany ───────────────────────────────────────────────────────────────
  'berlin': 'Europe/Berlin',
  'hamburg': 'Europe/Berlin',
  'munich': 'Europe/Berlin',
  'munchen': 'Europe/Berlin',
  'cologne': 'Europe/Berlin',
  'koln': 'Europe/Berlin',
  'frankfurt': 'Europe/Berlin',
  'stuttgart': 'Europe/Berlin',
  'dusseldorf': 'Europe/Berlin',
  'dortmund': 'Europe/Berlin',
  'essen': 'Europe/Berlin',
  'leipzig': 'Europe/Berlin',
  'bremen': 'Europe/Berlin',
  'dresden': 'Europe/Berlin',
  'hannover': 'Europe/Berlin',
  'nuremberg': 'Europe/Berlin',
  'nurnberg': 'Europe/Berlin',
  'duisburg': 'Europe/Berlin',
  'bochum': 'Europe/Berlin',
  'wuppertal': 'Europe/Berlin',
  'bielefeld': 'Europe/Berlin',
  'bonn': 'Europe/Berlin',
  'mannheim': 'Europe/Berlin',
  'karlsruhe': 'Europe/Berlin',
  'augsburg': 'Europe/Berlin',
  'wiesbaden': 'Europe/Berlin',
  'munster': 'Europe/Berlin',
  'freiburg': 'Europe/Berlin',
  'kiel': 'Europe/Berlin',
  'lubeck': 'Europe/Berlin',

  // ── Spain ─────────────────────────────────────────────────────────────────
  'madrid': 'Europe/Madrid',
  'barcelona': 'Europe/Madrid',
  'valencia': 'Europe/Madrid',
  'seville': 'Europe/Madrid',
  'sevilla': 'Europe/Madrid',
  'zaragoza': 'Europe/Madrid',
  'malaga': 'Europe/Madrid',
  'murcia': 'Europe/Madrid',
  'palma': 'Europe/Madrid',
  'las palmas': 'Atlantic/Canary',
  'bilbao': 'Europe/Madrid',
  'alicante': 'Europe/Madrid',
  'cordoba': 'Europe/Madrid',
  'valladolid': 'Europe/Madrid',
  'vigo': 'Europe/Madrid',
  'gijon': 'Europe/Madrid',
  'granada': 'Europe/Madrid',
  'tenerife': 'Atlantic/Canary',

  // ── Italy ─────────────────────────────────────────────────────────────────
  'rome': 'Europe/Rome',
  'roma': 'Europe/Rome',
  'milan': 'Europe/Rome',
  'milano': 'Europe/Rome',
  'naples': 'Europe/Rome',
  'napoli': 'Europe/Rome',
  'turin': 'Europe/Rome',
  'torino': 'Europe/Rome',
  'palermo': 'Europe/Rome',
  'genoa': 'Europe/Rome',
  'genova': 'Europe/Rome',
  'bologna': 'Europe/Rome',
  'florence': 'Europe/Rome',
  'firenze': 'Europe/Rome',
  'bari': 'Europe/Rome',
  'catania': 'Europe/Rome',
  'venice': 'Europe/Rome',
  'venezia': 'Europe/Rome',
  'verona': 'Europe/Rome',
  'padova': 'Europe/Rome',
  'trieste': 'Europe/Rome',
  'brescia': 'Europe/Rome',
  'parma': 'Europe/Rome',
  'modena': 'Europe/Rome',
  'pisa': 'Europe/Rome',
  'reggio': 'Europe/Rome',

  // ── Netherlands ───────────────────────────────────────────────────────────
  'amsterdam': 'Europe/Amsterdam',
  'rotterdam': 'Europe/Amsterdam',
  'the hague': 'Europe/Amsterdam',
  'den haag': 'Europe/Amsterdam',
  'utrecht': 'Europe/Amsterdam',
  'eindhoven': 'Europe/Amsterdam',
  'groningen': 'Europe/Amsterdam',
  'tilburg': 'Europe/Amsterdam',
  'almere': 'Europe/Amsterdam',
  'breda': 'Europe/Amsterdam',

  // ── Belgium ───────────────────────────────────────────────────────────────
  'brussels': 'Europe/Brussels',
  'bruxelles': 'Europe/Brussels',
  'antwerp': 'Europe/Brussels',
  'ghent': 'Europe/Brussels',
  'liege': 'Europe/Brussels',
  'bruges': 'Europe/Brussels',

  // ── Switzerland ───────────────────────────────────────────────────────────
  'zurich': 'Europe/Zurich',
  'geneva': 'Europe/Zurich',
  'bern': 'Europe/Zurich',
  'basel': 'Europe/Zurich',
  'lausanne': 'Europe/Zurich',

  // ── Austria ───────────────────────────────────────────────────────────────
  'vienna': 'Europe/Vienna',
  'wien': 'Europe/Vienna',
  'graz': 'Europe/Vienna',
  'linz': 'Europe/Vienna',
  'salzburg': 'Europe/Vienna',
  'innsbruck': 'Europe/Vienna',

  // ── Poland ────────────────────────────────────────────────────────────────
  'warsaw': 'Europe/Warsaw',
  'krakow': 'Europe/Warsaw',
  'lodz': 'Europe/Warsaw',
  'wroclaw': 'Europe/Warsaw',
  'poznan': 'Europe/Warsaw',
  'gdansk': 'Europe/Warsaw',
  'szczecin': 'Europe/Warsaw',
  'bydgoszcz': 'Europe/Warsaw',
  'lublin': 'Europe/Warsaw',
  'katowice': 'Europe/Warsaw',

  // ── Czech Republic ────────────────────────────────────────────────────────
  'prague': 'Europe/Prague',
  'brno': 'Europe/Prague',
  'ostrava': 'Europe/Prague',
  'plzen': 'Europe/Prague',

  // ── Hungary ───────────────────────────────────────────────────────────────
  'budapest': 'Europe/Budapest',
  'debrecen': 'Europe/Budapest',

  // ── Romania ───────────────────────────────────────────────────────────────
  'bucharest': 'Europe/Bucharest',
  'cluj': 'Europe/Bucharest',
  'timisoara': 'Europe/Bucharest',
  'iasi': 'Europe/Bucharest',
  'constanta': 'Europe/Bucharest',

  // ── Greece ────────────────────────────────────────────────────────────────
  'athens': 'Europe/Athens',
  'thessaloniki': 'Europe/Athens',
  'patras': 'Europe/Athens',
  'heraklion': 'Europe/Athens',

  // ── Portugal ──────────────────────────────────────────────────────────────
  'lisbon': 'Europe/Lisbon',
  'porto': 'Europe/Lisbon',
  'braga': 'Europe/Lisbon',
  'coimbra': 'Europe/Lisbon',

  // ── Sweden ────────────────────────────────────────────────────────────────
  'stockholm': 'Europe/Stockholm',
  'gothenburg': 'Europe/Stockholm',
  'malmo': 'Europe/Stockholm',
  'uppsala': 'Europe/Stockholm',

  // ── Norway ────────────────────────────────────────────────────────────────
  'oslo': 'Europe/Oslo',
  'bergen': 'Europe/Oslo',
  'trondheim': 'Europe/Oslo',
  'stavanger': 'Europe/Oslo',

  // ── Denmark ───────────────────────────────────────────────────────────────
  'copenhagen': 'Europe/Copenhagen',
  'aarhus': 'Europe/Copenhagen',
  'odense': 'Europe/Copenhagen',

  // ── Finland ───────────────────────────────────────────────────────────────
  'helsinki': 'Europe/Helsinki',
  'tampere': 'Europe/Helsinki',
  'turku': 'Europe/Helsinki',
  'oulu': 'Europe/Helsinki',

  // ── Russia ────────────────────────────────────────────────────────────────
  'moscow': 'Europe/Moscow',
  'st petersburg': 'Europe/Moscow',
  'saint petersburg': 'Europe/Moscow',
  'novosibirsk': 'Asia/Novosibirsk',
  'yekaterinburg': 'Asia/Yekaterinburg',
  'ekaterinburg': 'Asia/Yekaterinburg',
  'nizhny novgorod': 'Europe/Moscow',
  'kazan': 'Europe/Moscow',
  'chelyabinsk': 'Asia/Yekaterinburg',
  'omsk': 'Asia/Omsk',
  'samara': 'Europe/Samara',
  'rostov-on-don': 'Europe/Moscow',
  'ufa': 'Asia/Yekaterinburg',
  'krasnoyarsk': 'Asia/Krasnoyarsk',
  'vladivostok': 'Asia/Vladivostok',
  'irkutsk': 'Asia/Irkutsk',
  'volgograd': 'Europe/Volgograd',
  'perm': 'Asia/Yekaterinburg',

  // ── Ukraine ───────────────────────────────────────────────────────────────
  'kyiv': 'Europe/Kyiv',
  'kiev': 'Europe/Kyiv',
  'kharkiv': 'Europe/Kyiv',
  'odessa': 'Europe/Kyiv',
  'dnipro': 'Europe/Kyiv',
  'lviv': 'Europe/Kyiv',
  'zaporizhzhia': 'Europe/Kyiv',
  'kryvyi rih': 'Europe/Kyiv',

  // ── Turkey ────────────────────────────────────────────────────────────────
  'istanbul': 'Europe/Istanbul',
  'ankara': 'Europe/Istanbul',
  'izmir': 'Europe/Istanbul',
  'bursa': 'Europe/Istanbul',
  'adana': 'Europe/Istanbul',
  'antalya': 'Europe/Istanbul',
  'gaziantep': 'Europe/Istanbul',
  'konya': 'Europe/Istanbul',

  // ── China ─────────────────────────────────────────────────────────────────
  'beijing': 'Asia/Shanghai',
  'shanghai': 'Asia/Shanghai',
  'guangzhou': 'Asia/Shanghai',
  'shenzhen': 'Asia/Shanghai',
  'chengdu': 'Asia/Shanghai',
  'tianjin': 'Asia/Shanghai',
  'wuhan': 'Asia/Shanghai',
  'chongqing': 'Asia/Shanghai',
  'xian': 'Asia/Shanghai',
  "xi'an": 'Asia/Shanghai',
  'nanjing': 'Asia/Shanghai',
  'hangzhou': 'Asia/Shanghai',
  'shenyang': 'Asia/Shanghai',
  'qingdao': 'Asia/Shanghai',
  'hefei': 'Asia/Shanghai',
  'fuzhou': 'Asia/Shanghai',
  'zhengzhou': 'Asia/Shanghai',
  'jinan': 'Asia/Shanghai',
  'changsha': 'Asia/Shanghai',
  'dalian': 'Asia/Shanghai',
  'kunming': 'Asia/Shanghai',
  'harbin': 'Asia/Shanghai',
  'nanning': 'Asia/Shanghai',
  'taiyuan': 'Asia/Shanghai',
  'guiyang': 'Asia/Shanghai',
  'lanzhou': 'Asia/Shanghai',
  'urumqi': 'Asia/Urumqi',
  'lhasa': 'Asia/Shanghai',
  'hong kong': 'Asia/Hong_Kong',
  'kowloon': 'Asia/Hong_Kong',
  'macau': 'Asia/Macau',

  // ── Japan ─────────────────────────────────────────────────────────────────
  'tokyo': 'Asia/Tokyo',
  'yokohama': 'Asia/Tokyo',
  'osaka': 'Asia/Tokyo',
  'nagoya': 'Asia/Tokyo',
  'sapporo': 'Asia/Tokyo',
  'fukuoka': 'Asia/Tokyo',
  'kawasaki': 'Asia/Tokyo',
  'kobe': 'Asia/Tokyo',
  'kyoto': 'Asia/Tokyo',
  'saitama': 'Asia/Tokyo',
  'hiroshima': 'Asia/Tokyo',
  'sendai': 'Asia/Tokyo',
  'kitakyushu': 'Asia/Tokyo',
  'chiba': 'Asia/Tokyo',
  'sakai': 'Asia/Tokyo',
  'kumamoto': 'Asia/Tokyo',
  'okayama': 'Asia/Tokyo',
  'nagasaki': 'Asia/Tokyo',

  // ── South Korea ───────────────────────────────────────────────────────────
  'seoul': 'Asia/Seoul',
  'busan': 'Asia/Seoul',
  'incheon': 'Asia/Seoul',
  'daegu': 'Asia/Seoul',
  'daejeon': 'Asia/Seoul',
  'gwangju': 'Asia/Seoul',
  'suwon': 'Asia/Seoul',

  // ── India ─────────────────────────────────────────────────────────────────
  'mumbai': 'Asia/Kolkata',
  'bombay': 'Asia/Kolkata',
  'delhi': 'Asia/Kolkata',
  'new delhi': 'Asia/Kolkata',
  'bangalore': 'Asia/Kolkata',
  'bengaluru': 'Asia/Kolkata',
  'hyderabad': 'Asia/Kolkata',
  'ahmedabad': 'Asia/Kolkata',
  'chennai': 'Asia/Kolkata',
  'madras': 'Asia/Kolkata',
  'kolkata': 'Asia/Kolkata',
  'calcutta': 'Asia/Kolkata',
  'surat': 'Asia/Kolkata',
  'pune': 'Asia/Kolkata',
  'jaipur': 'Asia/Kolkata',
  'lucknow': 'Asia/Kolkata',
  'kanpur': 'Asia/Kolkata',
  'nagpur': 'Asia/Kolkata',
  'patna': 'Asia/Kolkata',
  'indore': 'Asia/Kolkata',
  'bhopal': 'Asia/Kolkata',
  'ludhiana': 'Asia/Kolkata',
  'agra': 'Asia/Kolkata',
  'vadodara': 'Asia/Kolkata',
  'coimbatore': 'Asia/Kolkata',
  'kochi': 'Asia/Kolkata',
  'cochin': 'Asia/Kolkata',
  'mysore': 'Asia/Kolkata',
  'mysuru': 'Asia/Kolkata',
  'gurgaon': 'Asia/Kolkata',
  'gurugram': 'Asia/Kolkata',
  'noida': 'Asia/Kolkata',
  'ghaziabad': 'Asia/Kolkata',
  'faridabad': 'Asia/Kolkata',
  'chandigarh': 'Asia/Kolkata',
  'amritsar': 'Asia/Kolkata',
  'visakhapatnam': 'Asia/Kolkata',
  'vizag': 'Asia/Kolkata',

  // ── Pakistan ──────────────────────────────────────────────────────────────
  'karachi': 'Asia/Karachi',
  'lahore': 'Asia/Karachi',
  'islamabad': 'Asia/Karachi',
  'rawalpindi': 'Asia/Karachi',
  'faisalabad': 'Asia/Karachi',
  'multan': 'Asia/Karachi',
  'peshawar': 'Asia/Karachi',
  'quetta': 'Asia/Karachi',

  // ── Bangladesh ────────────────────────────────────────────────────────────
  'dhaka': 'Asia/Dhaka',
  'chittagong': 'Asia/Dhaka',
  'khulna': 'Asia/Dhaka',
  'rajshahi': 'Asia/Dhaka',
  'sylhet': 'Asia/Dhaka',

  // ── Sri Lanka ─────────────────────────────────────────────────────────────
  'colombo': 'Asia/Colombo',
  'kandy': 'Asia/Colombo',

  // ── Nepal ─────────────────────────────────────────────────────────────────
  'kathmandu': 'Asia/Kathmandu',

  // ── Middle East ───────────────────────────────────────────────────────────
  'riyadh': 'Asia/Riyadh',
  'jeddah': 'Asia/Riyadh',
  'mecca': 'Asia/Riyadh',
  'medina': 'Asia/Riyadh',
  'dammam': 'Asia/Riyadh',
  'dubai': 'Asia/Dubai',
  'abu dhabi': 'Asia/Dubai',
  'sharjah': 'Asia/Dubai',
  'ajman': 'Asia/Dubai',
  'doha': 'Asia/Qatar',
  'kuwait city': 'Asia/Kuwait',
  'muscat': 'Asia/Muscat',
  'manama': 'Asia/Bahrain',
  'amman': 'Asia/Amman',
  'beirut': 'Asia/Beirut',
  'damascus': 'Asia/Damascus',
  'baghdad': 'Asia/Baghdad',
  'basra': 'Asia/Baghdad',
  'tehran': 'Asia/Tehran',
  'mashhad': 'Asia/Tehran',
  'isfahan': 'Asia/Tehran',
  'shiraz': 'Asia/Tehran',
  'tabriz': 'Asia/Tehran',
  'tel aviv': 'Asia/Jerusalem',
  'jerusalem': 'Asia/Jerusalem',
  'haifa': 'Asia/Jerusalem',

  // ── Southeast Asia ────────────────────────────────────────────────────────
  'singapore': 'Asia/Singapore',
  'jakarta': 'Asia/Jakarta',
  'surabaya': 'Asia/Jakarta',
  'bandung': 'Asia/Jakarta',
  'medan': 'Asia/Jakarta',
  'bali': 'Asia/Makassar',
  'denpasar': 'Asia/Makassar',
  'makassar': 'Asia/Makassar',
  'kuala lumpur': 'Asia/Kuala_Lumpur',
  'kl': 'Asia/Kuala_Lumpur',
  'penang': 'Asia/Kuala_Lumpur',
  'johor bahru': 'Asia/Kuala_Lumpur',
  'manila': 'Asia/Manila',
  'quezon city': 'Asia/Manila',
  'davao': 'Asia/Manila',
  'cebu': 'Asia/Manila',
  'bangkok': 'Asia/Bangkok',
  'chiang mai': 'Asia/Bangkok',
  'pattaya': 'Asia/Bangkok',
  'phuket': 'Asia/Bangkok',
  'ho chi minh': 'Asia/Ho_Chi_Minh',
  'saigon': 'Asia/Ho_Chi_Minh',
  'hanoi': 'Asia/Bangkok',
  'da nang': 'Asia/Bangkok',
  'phnom penh': 'Asia/Phnom_Penh',
  'vientiane': 'Asia/Vientiane',
  'yangon': 'Asia/Yangon',
  'rangoon': 'Asia/Yangon',
  'naypyidaw': 'Asia/Yangon',
  'colombo sri lanka': 'Asia/Colombo',
  'dhaka bangladesh': 'Asia/Dhaka',
  'kathmandu nepal': 'Asia/Kathmandu',
  'brunei': 'Asia/Brunei',
  'bandar seri begawan': 'Asia/Brunei',
  'dili': 'Asia/Dili',
  'ulaanbaatar': 'Asia/Ulaanbaatar',

  // ── Taiwan ────────────────────────────────────────────────────────────────
  'taipei': 'Asia/Taipei',
  'kaohsiung': 'Asia/Taipei',
  'taichung': 'Asia/Taipei',
  'tainan': 'Asia/Taipei',

  // ── Australia ─────────────────────────────────────────────────────────────
  'sydney': 'Australia/Sydney',
  'melbourne': 'Australia/Melbourne',
  'brisbane': 'Australia/Brisbane',
  'perth': 'Australia/Perth',
  'adelaide': 'Australia/Adelaide',
  'canberra': 'Australia/Sydney',
  'gold coast': 'Australia/Brisbane',
  'newcastle au': 'Australia/Sydney',
  'wollongong': 'Australia/Sydney',
  'hobart': 'Australia/Hobart',
  'darwin': 'Australia/Darwin',
  'townsville': 'Australia/Brisbane',
  'cairns': 'Australia/Brisbane',
  'geelong': 'Australia/Melbourne',
  'sunshine coast': 'Australia/Brisbane',

  // ── New Zealand ───────────────────────────────────────────────────────────
  'auckland': 'Pacific/Auckland',
  'wellington': 'Pacific/Auckland',
  'christchurch': 'Pacific/Auckland',
  'hamilton nz': 'Pacific/Auckland',
  'tauranga': 'Pacific/Auckland',
  'dunedin': 'Pacific/Auckland',

  // ── Africa ────────────────────────────────────────────────────────────────
  'cairo': 'Africa/Cairo',
  'alexandria egypt': 'Africa/Cairo',
  'giza': 'Africa/Cairo',
  'lagos': 'Africa/Lagos',
  'abuja': 'Africa/Lagos',
  'ibadan': 'Africa/Lagos',
  'kano': 'Africa/Lagos',
  'port harcourt': 'Africa/Lagos',
  'nairobi': 'Africa/Nairobi',
  'mombasa': 'Africa/Nairobi',
  'dar es salaam': 'Africa/Dar_es_Salaam',
  'addis ababa': 'Africa/Addis_Ababa',
  'johannesburg': 'Africa/Johannesburg',
  'cape town': 'Africa/Johannesburg',
  'durban': 'Africa/Johannesburg',
  'pretoria': 'Africa/Johannesburg',
  'soweto': 'Africa/Johannesburg',
  'accra': 'Africa/Accra',
  'kumasi': 'Africa/Accra',
  'dakar': 'Africa/Dakar',
  'casablanca': 'Africa/Casablanca',
  'rabat': 'Africa/Casablanca',
  'marrakech': 'Africa/Casablanca',
  'marrakesh': 'Africa/Casablanca',
  'fes': 'Africa/Casablanca',
  'algiers': 'Africa/Algiers',
  'tunis': 'Africa/Tunis',
  'tripoli': 'Africa/Tripoli',
  'khartoum': 'Africa/Khartoum',
  'kampala': 'Africa/Kampala',
  'lusaka': 'Africa/Lusaka',
  'harare': 'Africa/Harare',
  'maputo': 'Africa/Maputo',
  'antananarivo': 'Indian/Antananarivo',
  'kinshasa': 'Africa/Kinshasa',
  'luanda': 'Africa/Luanda',
  'brazzaville': 'Africa/Brazzaville',
  'douala': 'Africa/Douala',
  'yaounde': 'Africa/Douala',
  'abidjan': 'Africa/Abidjan',
  'bamako': 'Africa/Bamako',
  'conakry': 'Africa/Conakry',
  'freetown': 'Africa/Freetown',
  'monrovia': 'Africa/Monrovia',
  'lome': 'Africa/Lome',
  'cotonou': 'Africa/Porto-Novo',
  'niamey': 'Africa/Niamey',
  'ouagadougou': 'Africa/Ouagadougou',
  'ndjamena': 'Africa/Ndjamena',
  'kigali': 'Africa/Kigali',
  'bujumbura': 'Africa/Bujumbura',
  'lilongwe': 'Africa/Blantyre',
  'windhoek': 'Africa/Windhoek',
  'gaborone': 'Africa/Gaborone',
  'maseru': 'Africa/Maseru',
  'mbabane': 'Africa/Mbabane',
  'mogadishu': 'Africa/Mogadishu',
  'djibouti': 'Africa/Djibouti',
  'asmara': 'Africa/Asmara',

  // ── South America ─────────────────────────────────────────────────────────
  'sao paulo': 'America/Sao_Paulo',
  'são paulo': 'America/Sao_Paulo',
  'rio de janeiro': 'America/Sao_Paulo',
  'rio': 'America/Sao_Paulo',
  'brasilia': 'America/Sao_Paulo',
  'salvador': 'America/Bahia',
  'fortaleza': 'America/Fortaleza',
  'belo horizonte': 'America/Sao_Paulo',
  'manaus': 'America/Manaus',
  'curitiba': 'America/Sao_Paulo',
  'recife': 'America/Recife',
  'porto alegre': 'America/Sao_Paulo',
  'belem': 'America/Belem',
  'belem brazil': 'America/Belem',
  'goiania': 'America/Sao_Paulo',
  'buenos aires': 'America/Argentina/Buenos_Aires',
  'cordoba argentina': 'America/Argentina/Cordoba',
  'rosario': 'America/Argentina/Cordoba',
  'mendoza': 'America/Argentina/Mendoza',
  'santiago': 'America/Santiago',
  'valparaiso': 'America/Santiago',
  'lima': 'America/Lima',
  'arequipa': 'America/Lima',
  'bogota': 'America/Bogota',
  'medellin': 'America/Bogota',
  'cali': 'America/Bogota',
  'caracas': 'America/Caracas',
  'maracaibo': 'America/Caracas',
  'quito': 'America/Guayaquil',
  'guayaquil': 'America/Guayaquil',
  'la paz': 'America/La_Paz',
  'cochabamba': 'America/La_Paz',
  'asuncion': 'America/Asuncion',
  'montevideo': 'America/Montevideo',
  'georgetown': 'America/Guyana',
  'paramaribo': 'America/Paramaribo',
  'cayenne': 'America/Cayenne',
  'panama city': 'America/Panama',
  'san jose cr': 'America/Costa_Rica',
  'san jose costa rica': 'America/Costa_Rica',
  'guatemala city': 'America/Guatemala',
  'tegucigalpa': 'America/Tegucigalpa',
  'managua': 'America/Managua',
  'san salvador': 'America/El_Salvador',
  'havana': 'America/Havana',
  'santo domingo': 'America/Santo_Domingo',
  'san juan pr': 'America/Puerto_Rico',
  'san juan puerto rico': 'America/Puerto_Rico',
  'port-au-prince': 'America/Port-au-Prince',
  'kingston': 'America/Jamaica',
  'nassau': 'America/Nassau',
  'hamilton bermuda': 'Atlantic/Bermuda',
  'bridgetown': 'America/Barbados',
  'port of spain': 'America/Port_of_Spain',

  // ── Central Asia ──────────────────────────────────────────────────────────
  'almaty': 'Asia/Almaty',
  'nur-sultan': 'Asia/Almaty',
  'astana': 'Asia/Almaty',
  'tashkent': 'Asia/Tashkent',
  'bishkek': 'Asia/Bishkek',
  'dushanbe': 'Asia/Dushanbe',
  'ashgabat': 'Asia/Ashgabat',
  'baku': 'Asia/Baku',
  'yerevan': 'Asia/Yerevan',
  'tbilisi': 'Asia/Tbilisi',

  // ── Pacific ───────────────────────────────────────────────────────────────
  'suva': 'Pacific/Fiji',
  'nuku\'alofa': 'Pacific/Tongatapu',
  'apia': 'Pacific/Apia',
  'pago pago': 'Pacific/Pago_Pago',
  'noumea': 'Pacific/Noumea',
  'port moresby': 'Pacific/Port_Moresby',
  'honiara': 'Pacific/Guadalcanal',
  'vanuatu': 'Pacific/Efate',
  'port vila': 'Pacific/Efate',
  'funafuti': 'Pacific/Funafuti',
  'tarawa': 'Pacific/Tarawa',

  // ── Iceland ───────────────────────────────────────────────────────────────
  'reykjavik': 'Atlantic/Reykjavik',

  // ── Balkans ───────────────────────────────────────────────────────────────
  'belgrade': 'Europe/Belgrade',
  'zagreb': 'Europe/Zagreb',
  'ljubljana': 'Europe/Ljubljana',
  'sarajevo': 'Europe/Sarajevo',
  'skopje': 'Europe/Skopje',
  'podgorica': 'Europe/Podgorica',
  'tirana': 'Europe/Tirane',
  'sofia': 'Europe/Sofia',
  'riga': 'Europe/Riga',
  'tallinn': 'Europe/Tallinn',
  'vilnius': 'Europe/Vilnius',
  'minsk': 'Europe/Minsk',
  'chisinau': 'Europe/Chisinau',
  'nicosia': 'Asia/Nicosia',
  'valletta': 'Europe/Malta',

  // ── Scandinavia extra ─────────────────────────────────────────────────────
  'torshavn': 'Atlantic/Faroe',
  'nuuk': 'America/Nuuk',
  'reykjavik iceland': 'Atlantic/Reykjavik',
};
